### PR TITLE
Added alpha_transparency option & tests

### PR DESCRIPTION
**Pull request by nightvision04**

### CODE REVIEW

**Comment by nightvision04** [comment]
I just added a pytest workflow because I noticed there wasn't one.

**Comment by erdogant** [comment]
Nice!

**Comment by nightvision04** [comment]
Okay, I had to tweak some of the directory structure to allow your tests to be implemented in CI. 

Should be good to go!

If you remove the colourmap dependency, you'll be able to support osx users as well . :)

**Comment by nightvision04** [comment]
For some reason the conda builds were running extremely slow on windows. Ubuntu was fine. I've disabled them for now but feel free to add them back.

**Comment by erdogant** [comment]
I created a new version! 
https://github.com/erdogant/pca/releases/tag/1.5.0

`pip install -U pca`

**Pull request merged**
